<a href="https://colab.research.google.com/github/hyunyongPark/Recommendation/blob/master/wearly_graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. data load & preprocessing**

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
!pip uninstall tensorflow

In [ ]:
!pip install tensorflow==1.7

In [ ]:
import numpy as np
import pandas as pd
import json
import time
from collections import deque

import tensorflow as tf
from six import next
from sklearn import preprocessing
import sys
from scipy.sparse import lil_matrix
from scipy.sparse import coo_matrix
tf.__version__

'1.7.0'

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/


In [ ]:
def make_userANDrate():
  credentials = "postgresql://jczdtzmaouemml:f3f55cc0c6bd25a42866864c9299f4ec79ff4ff890f6f69467e2b14dc0010074@ec2-3-215-207-12.compute-1.amazonaws.com:5432/de8i6u9p9i6vq8"
  dbdf = pd.read_sql("""select distinct * from wearly_user where age <= 70 order by idx """, con = credentials)
  item = pd.read_sql("""select * from wearly_wear""", con = credentials)
  df = dbdf.copy()
  df = df.drop_duplicates(['name', 'gender', 'age']+ df.columns.tolist()[4:-1], keep='first').reset_index(drop=False)
  df = df.drop(['index','name','idx','time'], axis=1 , inplace=False)
  
  v = [data_row.values.tolist()[2:] for index, data_row in df.iterrows()]
  vv = [v[i][j] for i in range(len(v)) for j in range(len(v[i]))]

  user_rt = pd.DataFrame(index=range(0,len(df)*100) , columns=['user','image_file_name', 'rate'])
  user_rt['user'] = sorted([i for i in range(0,len(df)) for j in range(0,100)])
  user_rt['image_file_name'] = vv

  for i in range(len(user_rt)):
    user_rt['rate'][i] = int(user_rt['image_file_name'][i][-1])
    user_rt['image_file_name'][i] = str(user_rt['image_file_name'][i][:-1])
  
  user_rt = user_rt.sample(frac=1, random_state=200).reset_index(drop=True)
  user_rt = user_rt.merge(item[['image_id', 'image_file_name']], on='image_file_name')
  
  for i in range(len(user_rt)):
    if user_rt['rate'][i] == 3:
      user_rt['rate'][i] = 2
    elif user_rt['rate'][i] == 5:
      user_rt['rate'][i] = 3
    else:
      user_rt['rate'][i] = user_rt['rate'][i] 

    PERC = 0.9
    rows = len(user_rt)
    split_index = int(rows * PERC)
    df_train = user_rt[0:split_index]
    df_test = user_rt[split_index:].reset_index(drop=True)
    
    user_mt = df[['age','gender']]
    user_mt = user_mt.reset_index()
    user_mt['user'] = user_mt['index']
    user_mt = user_mt[['user', 'age', 'gender']]
    
  return user_mt , user_rt, df_train, df_test , item

user_mt, user_rt , df_train, df_test, item = make_userANDrate()

In [ ]:
## user_mt  one_hot encoding
user_mt2 = pd.get_dummies(user_mt, columns=[ "age", "gender"])
user_mt2 = user_mt2.values

In [ ]:
item2 = item.drop(['idx', 'post_id', 'hashtag_crawl', 'account_name', 'image_file_name'], axis=1, inplace=False)
item2 = item2.values

In [ ]:
train = df_train[['user','image_id', 'rate']]
test = df_test[['user','image_id', 'rate']]

# **2. GraphRec modeling**

In [ ]:
class ShuffleIterator(object): 

    def __init__(self, inputs, batch_size=10):
        self.inputs = inputs
        self.batch_size = batch_size
        self.num_cols = len(self.inputs)  # 행의 갯수
        self.len = len(self.inputs[0]) # 열의 갯수
        self.inputs = np.transpose(np.vstack([np.array(self.inputs[i]) for i in range(self.num_cols)])) # inputs가 i마다 밑으로 쌓임. -> 그걸 전치시킴

    def __len__(self):
        return self.len

    def __iter__(self):
        return self

    def __next__(self):
        return self.next()

    def next(self):  
        ids = np.random.randint(0, self.len, (self.batch_size,))  # 0부터 기존행의개수까지 배치사이즈만큼 랜덤정수뽑음
        out = self.inputs[ids, :] # 이런 랜덤정수index에 해당하는 모든 열   ->   열*행에서 열의 개수 만큼 뽑아냄
        return [out[:, i] for i in range(self.num_cols)] # 열*행out에서 행의 넘버에 해당하는 모든 index를 뽑아냄 . 즉 원래모형으로 배치사이즈 크기에 값들이 셔플이 됨.  

In [ ]:
class OneEpochIterator(ShuffleIterator):
    def __init__(self, inputs, batch_size=10):
        super(OneEpochIterator, self).__init__(inputs, batch_size=batch_size) # 부모클래스의 inputs와 배치사이즈를 가져옴
        if batch_size > 0:
            self.idx_group = np.array_split(np.arange(self.len), np.ceil(self.len / batch_size))  # inputs길이크기의 array를 inputs길이/배치사이즈를 올림후의 크기의 갯수만큼 split하여 그 수만큼의 array 리스트 형성
        else: # 배치사이즈 적용안할경우
            self.idx_group = [np.arange(self.len)] 
        self.group_id = 0

    def next(self):
        if self.group_id >= len(self.idx_group):
            self.group_id = 0
            raise StopIteration
        out = self.inputs[self.idx_group[self.group_id], :]
        self.group_id += 1
        return [out[:, i] for i in range(self.num_cols)]

In [ ]:
def inferenceDense(phase,user_batch, item_batch,idx_user,idx_item, user_num, item_num,UReg=0.05,IReg=0.1):
    with tf.device(DEVICE):
        user_batch = tf.nn.embedding_lookup(idx_user, user_batch, name="embedding_user")
        item_batch = tf.nn.embedding_lookup(idx_item, item_batch, name="embedding_item")
        
        
        ul1mf=tf.layers.dense(inputs=user_batch, units=MFSIZE,activation=tf.nn.crelu, kernel_initializer=tf.random_normal_initializer(stddev=0.01))
        il1mf=tf.layers.dense(inputs=item_batch, units=MFSIZE,activation=tf.nn.crelu, kernel_initializer=tf.random_normal_initializer(stddev=0.01))
        InferInputMF=tf.multiply(ul1mf, il1mf)


        infer=tf.reduce_sum(InferInputMF, 1, name="inference")

        regularizer = tf.add(UW*tf.nn.l2_loss(ul1mf), IW*tf.nn.l2_loss(il1mf), name="regularizer")

    return InferInputMF, infer, regularizer

In [ ]:
def optimization(infer, regularizer, rate_batch, learning_rate=0.0005, reg=0.1):
    with tf.device(DEVICE):
        global_step = tf.train.get_global_step()
        assert global_step is not None
        cost_l2 = tf.nn.l2_loss(tf.subtract(infer, rate_batch))
        cost = tf.add(cost_l2, regularizer)
        train_op = tf.train.AdamOptimizer(learning_rate).minimize(cost, global_step=global_step)
    return cost, train_op

In [ ]:
def clip(x):
    return np.clip(x, 1.0, 3.0)


In [ ]:
def GraphRec(train, test,ItmDat,UsrDat,Graph=True,Dataset='100k'):  # 아이템정보와 유저정보를 사용할지 말지를 정함.

    AdjacencyUsers = np.zeros((USER_NUM,ITEM_NUM), dtype=np.float32) #np.asarray([[0 for x in range(ITEM_NUM)] for y in range(USER_NUM)],dtype=np.float16)
    #print('AdjacencyUsers : ' , AdjacencyUsers.shape)  # (943, 1682)
    DegreeUsers = np.zeros((USER_NUM,1), dtype=np.float32)# np.asarray([[0 for x in range(1)] for y in range(USER_NUM)],dtype=np.float16)
    #print('DegreeUsers : ' , DegreeUsers.shape) # (943, 1)
    AdjacencyItems = np.zeros((ITEM_NUM,USER_NUM), dtype=np.float32) #np.asarray([[0 for x in range(USER_NUM)] for y in range(ITEM_NUM)],dtype=np.float16)
    #print('AdjacencyItems : ' , AdjacencyItems.shape) # (1682, 943)
    DegreeItems =  np.zeros((ITEM_NUM,1), dtype=np.float32) #np.asarray([[0 for x in range(1)] for y in range(ITEM_NUM)],dtype=np.float16)
    #print('DegreeItems : ' , DegreeItems.shape) # (1682, 1)
    
    for index, row in train.iterrows():
      userid=int(row['user'])  # train의 user(길이9000)를 하나하나 접근 
      itemid=int(row['image_id'])
      
      # 인접행렬 형성  
      AdjacencyUsers[userid][itemid]=row['rate']/3.0   # 인접행렬 정규화   train의 rate를 max_rate로 나누어줌으로서 정규화
      AdjacencyItems[itemid][userid]=row['rate']/3.0   # 이렇게 되면 결국 train에 존재하는 유저는 정규화된 평점이 찍히고 나머지는 0    /결국은 유저와 아이템의 rate기반 인접된 행렬 형성
      
      DegreeUsers[userid][0]+=1    # 중복된 user의 수를 볼수있음. 예를들면 userid가 880인데 for문돌면서 몇번나왔는지 찍힘.  
      #print(userid, ' : ', DegreeUsers[userid])
      DegreeItems[itemid][0]+=1  # 같은의미로 itemid의 등장빈도확인가능
      #DegreeUsers shape : (943,1)   /  DegreeItems shape : (1682, 1)

    DUserMax=np.amax(DegreeUsers)  # amax는 array의 최댓값 반환.   654    -> 제일 많이 등장한 user빈도가 
    #print(DUserMax)
    DItemMax=np.amax(DegreeItems)
    DegreeUsers=np.true_divide(DegreeUsers, DUserMax) # np.true_divide는 나눗셈반환    (라플라시안 벡터 정규화 (공부필요))  
    DegreeItems=np.true_divide(DegreeItems, DItemMax)
    
    # weighted AdjacencyUsers vec
    AdjacencyUsers=np.asarray(AdjacencyUsers,dtype=np.float32)
    AdjacencyItems=np.asarray(AdjacencyItems,dtype=np.float32)
    print('인접행렬Au : ', AdjacencyUsers.shape)
    print('인접행렬Ai : ',AdjacencyItems.shape)
    if(Graph):   #943*943 + 943*1682 + 943*1          #1682*1682 + 1682*943 + 1682*1
        UserFeatures= np.concatenate((np.identity(USER_NUM,dtype=np.bool_), AdjacencyUsers,DegreeUsers), axis=1) # L_u = Iu*Au*Du     실제로 저 단위정방행렬I는 없어도 됨.
        ItemFeatures= np.concatenate((np.identity(ITEM_NUM,dtype=np.bool_), AdjacencyItems,DegreeItems), axis=1) # L_i = Iu*Au*Du
    else:
        UserFeatures=np.identity(USER_NUM,dtype=np.bool_) # 왜 이것만 썻냐면 만약 GraphRec에서의 핵심인 라플라시안행렬분해를 쓰지않으면 자기자신을 그대로 씀. 즉 UserFeature는 아래에서 X_u 그 자체가 되어버림.
        ItemFeatures=np.identity(ITEM_NUM,dtype=np.bool_)

    print('유저피처스1 : ',  UserFeatures)
    print(UserFeatures.shape) # 943*2626

    print('아이템피처스1 : ',  ItemFeatures)
    print(ItemFeatures.shape) # 1682*2626

    UserFeatures=np.concatenate((UserFeatures,UsrDat), axis=1)  # X_u

    ItemFeatures=np.concatenate((ItemFeatures,ItmDat), axis=1) # X_i

    UserFeaturesLength=UserFeatures.shape[1]
    ItemFeaturesLength=ItemFeatures.shape[1]

    print('유저피처스2 : ',  UserFeatures)
    print('UserFeatures : ', UserFeatures.shape)
    print('아이템피처스2 : ',  ItemFeatures)
    print('ItemFeatures : ', ItemFeatures.shape)
    # ---------------------------------
    
    samples_per_batch = len(train) // BATCH_SIZE

    iter_train = ShuffleIterator([train["user"],train["image_id"],train["rate"]],batch_size=BATCH_SIZE)

    iter_test = OneEpochIterator([test["user"],test["image_id"],test["rate"]],batch_size=10000)


    user_batch = tf.placeholder(tf.int32, shape=[None], name="id_user")  #int형 plac 선언
    item_batch = tf.placeholder(tf.int32, shape=[None], name="id_item")
    rate_batch = tf.placeholder(tf.float64, shape=[None])
    phase = tf.placeholder(tf.bool, name='phase')
    
    
    w_user = tf.constant(UserFeatures,name="userids", shape=[USER_NUM,UserFeatures.shape[1]],dtype=tf.float64) # shape = [943,2710] 
    w_item = tf.constant(ItemFeatures,name="itemids", shape=[ITEM_NUM, ItemFeatures.shape[1]],dtype=tf.float64) # shape = [1682,2646]


    InferInputMF , infer, regularizer = inferenceDense(phase,user_batch, item_batch,w_user,w_item, user_num=USER_NUM, item_num=ITEM_NUM)
    global_step = tf.contrib.framework.get_or_create_global_step()
    _, train_op = optimization(infer, regularizer, rate_batch, learning_rate=LR, reg=0.09)

    init_op = tf.global_variables_initializer()
    config = tf.ConfigProto()
    config.gpu_options.per_process_gpu_memory_fraction = 0.5
    finalerror=-1
    with tf.Session(config=config) as sess:
        sess.run(init_op)
        print("{} {} {} {}".format("epoch", "train_error", "val_error", "elapsed_time"))
        errors = deque(maxlen=samples_per_batch)
        start = time.time()
        for i in range(EPOCH_MAX * samples_per_batch):
            #users, items, rates,y,m,d,dw,dy,w = next(iter_train)
            users, items, rates = next(iter_train)
            _, pred_batch = sess.run([train_op, infer], feed_dict={user_batch: users,
                                                                   item_batch: items,
                                                                   rate_batch: rates,
                                                                   phase:True})
            pred_batch = clip(pred_batch)
            errors.append(np.power(pred_batch - rates, 2))
            if i % samples_per_batch == 0:
                train_err = np.sqrt(np.mean(errors))
                test_err2 = np.array([])
                degreelist=list()
                predlist=list()
                for users, items, rates in iter_test:
                    pred_batch = sess.run(infer, feed_dict={user_batch: users,
                                                            item_batch: items,                                                                                             
                                                            phase:False})

                    pred_batch = clip(pred_batch)            
                    test_err2 = np.append(test_err2, np.power(pred_batch - rates, 2))
                end = time.time()
                test_err = np.sqrt(np.mean(test_err2))
                finalerror=test_err
                print("{:3d},{:f},{:f},{:f}(s)".format(i // samples_per_batch, train_err, test_err, end - start))
                start = end
    return InferInputMF

In [ ]:
DEVICE="/CPU:0"

In [ ]:
BATCH_SIZE = 1000
USER_NUM = len(user_mt2)
ITEM_NUM = len(item2)


MFSIZE=40
UW=0.08
IW=0.06
LR=0.0002
EPOCH_MAX = 50  #601
tf.reset_default_graph()
InferInputMF = GraphRec(train, test, item2, user_mt2, Graph=True)

인접행렬Au :  (307, 7628)
인접행렬Ai :  (7628, 307)
유저피처스1 :  [[1.         0.         0.         ... 0.         0.         0.9484536 ]
 [0.         1.         0.         ... 0.         0.         0.96907216]
 [0.         0.         1.         ... 0.         0.         0.87628865]
 ...
 [0.         0.         0.         ... 0.         0.         0.8659794 ]
 [0.         0.         0.         ... 0.         0.         0.9381443 ]
 [0.         0.         0.         ... 0.         0.         0.96907216]]
(307, 7936)
아이템피처스1 :  [[1.         0.         0.         ... 0.         0.         0.41666666]
 [0.         1.         0.         ... 0.         0.         0.5       ]
 [0.         0.         1.         ... 0.         0.         0.33333334]
 ...
 [0.         0.         0.         ... 0.         0.         0.6666667 ]
 [0.         0.         0.         ... 0.         0.         0.08333334]
 [0.         0.         0.         ... 0.         0.         0.        ]]
(7628, 7936)
유저피처스2 :  [[1. 0. 0. .